#!/bin/bash

. /opt/helpers

service influxdb start

# Allow any signal which would kill a process to stop server
trap "service influxdb stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u influxdb influxd > /dev/null; do sleep 5; done
