{
 "title": "Liferay",
 "description": "Liferay Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM \"ping4\" WITH KEY = \"hostname\" WHERE \"server_type\" =~ /Liferay/"
   },
   {
    "name": "disk",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"metric\" WHERE \"hostname\" =~ /^$hostname$/"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Alive",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "ping4",
     "query": "SELECT last(\"state\") FROM \"ping4\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "centreon_check_uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "packetloss",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "pl" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "rta",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "rta" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "WARNING",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "rta" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "CRITICAL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "crit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "rta" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "DOWNTIME",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping4",
     "select": [
      [
       { "params": [ "downtime_depth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "rta" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_cpu",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "!=", "value": "total_cpu_avg" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_memory",
     "query": "SELECT mean(\"value\") FROM \"centreon_check_memory\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval), \"metric\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "max_mem",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_memory",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Web",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_metric",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "http",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "time_connect" }
       ]
      },
      {
       "alias": "$tag_metric",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "http",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": " time_headers" }
       ]
      },
      {
       "alias": "$tag_metric",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "http",
       "query": "SELECT mean(\"value\") FROM \"http\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = ' time_headers') AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "time_transfer" }
       ]
      }
     ]
    },
    {
     "title": "Apache status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_metric",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "check_apache_status",
       "query": "SELECT mean(\"value\") FROM \"http\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'time') AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "Requests/sec" }
       ]
      },
      {
       "alias": "$tag_metric",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "check_apache_status",
       "query": "SELECT mean(\"value\") FROM \"http\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'time') AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "Open slot" }
       ]
      },
      {
       "alias": "$tag_metric",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "check_apache_status",
       "query": "SELECT mean(\"value\") FROM \"check_apache_status\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'Reading Request') AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "Reading Request" }
       ]
      },
      {
       "alias": "$tag_metric",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "check_apache_status",
       "query": "SELECT mean(\"value\") FROM \"check_apache_status\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'Reading Request') AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "Sending Reply" }
       ]
      },
      {
       "alias": "$tag_metric",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "metric" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "check_apache_status",
       "query": "SELECT mean(\"value\") FROM \"check_apache_status\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'Reading Request') AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "metric", "operator": "=", "value": "Waiting for Connection" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Heap memory use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^HeapMemoryUsage/" }
     ]
    }
   ]
  },
  {
   "title": "NonHeap memory use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^NonHeapMemoryUsage/" }
     ]
    }
   ]
  },
  {
   "title": "MemoryPool Metaspace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/jmx_memorypool_metaspace/" }
     ]
    }
   ]
  },
  {
   "title": "MemoryPool PS Edenspace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/jmx_memorypool_psedenspace/" }
     ]
    }
   ]
  },
  {
   "title": "MemoryPool PS Old Gen",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/jmx_memorypool_psoldgen/" }
     ]
    }
   ]
  },
  {
   "title": "MemoryPool PS Survivor space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=~",
       "value": "/jmx_memorypool_pssurvivorspace/"
      }
     ]
    }
   ]
  },
  {
   "title": "GarbageCollector  PS MarkSweep",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT mean(\"value\") FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" ~= 'jmx_garbagecollector_psmarksweep') AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=~",
       "value": "/jmx_garbagecollector_psmarksweep/"
      },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/Count/" }
     ]
    }
   ]
  },
  {
   "title": "GarbageCollector  PS Scavenge",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT mean(\"value\") FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /jmx_garbagecollector_psscavenge/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=~",
       "value": "/jmx_garbagecollector_psscavenge/"
      },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/Count/" }
     ]
    }
   ]
  },
  {
   "title": "Thread",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/jmx_threading/" },
      { "condition": "AND", "key": "metric", "operator": "!~", "value": "/Time/" },
      { "condition": "AND", "key": "metric", "operator": "!~", "value": "/Total/" }
     ]
    }
   ]
  },
  {
   "title": "ClassLoading",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/jmx_classloading/" }
     ]
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT mean(\"value\") FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^tomcat_globalrequest/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=",
       "value": "tomcat_globalrequestprocessor_requestCount"
      }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT mean(\"value\") FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^tomcat_globalrequest/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=",
       "value": "tomcat_globalrequestprocessor_errorCount"
      }
     ]
    }
   ]
  },
  {
   "title": "Proccessing time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT mean(\"value\") FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^tomcat_globalrequest/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=",
       "value": "tomcat_globalrequestprocessor_processingTime"
      }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT mean(\"value\") FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^tomcat_globalrequest/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=",
       "value": "tomcat_globalrequestprocessor_maxTime"
      }
     ]
    }
   ]
  },
  {
   "title": "Througput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT mean(\"value\") FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^tomcat_globalrequest/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=",
       "value": "tomcat_globalrequestprocessor_bytesReceived"
      }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT mean(\"value\") FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /^tomcat_globalrequest/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "service",
       "operator": "=",
       "value": "tomcat_globalrequestprocessor_bytesSent"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT difference(mean(\"value\")) FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /tomcat_threadpool/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/tomcat_threadpool/" }
     ]
    }
   ]
  },
  { "title": "Liferay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Portal Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT difference(mean(\"value\")) FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /tomcat_threadpool/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/liferay_portalmanager/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/Count/" }
     ]
    }
   ]
  },
  {
   "title": "Portal Request time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT difference(mean(\"value\")) FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /tomcat_threadpool/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/liferay_portalmanager/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/Time/" },
      { "condition": "AND", "key": "metric", "operator": "!~", "value": "/Count/" }
     ]
    }
   ]
  },
  {
   "title": "Porlet Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT difference(mean(\"value\")) FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /tomcat_threadpool/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/liferay_actionrequestportlet/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/Count/" }
     ]
    }
   ]
  },
  {
   "title": "Porlet Request time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "check_jmx",
     "query": "SELECT difference(mean(\"value\")) FROM \"check_jmx\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"service\" =~ /tomcat_threadpool/) AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/liferay_actionrequestportlet/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/Time/" },
      { "condition": "AND", "key": "metric", "operator": "!~", "value": "/Count/" }
     ]
    }
   ]
  },
  { "title": "MySQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "MySQL max query time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "$tag_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql_query",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "mysql-sql_max_query_time" }
     ]
    }
   ]
  },
  {
   "title": "MySQL slow queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql_query",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "mysql-sql_long_queries" }
     ]
    }
   ]
  },
  {
   "title": "MySQL tables",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Open_files" }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Open_tables" }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Table_locks_waited" }
     ]
    }
   ]
  },
  {
   "title": "MySQL Thread",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Threads_connected" }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Threads_running" }
     ]
    }
   ]
  },
  {
   "title": "MySQL queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Queries" }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "query": "SELECT difference(mean(\"value\")) FROM \"mysql\" WHERE (\"hostname\" =~ /^$hostname$/ AND \"metric\" = 'Questions') AND $timeFilter GROUP BY time($__interval), \"metric\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Questions" }
     ]
    }
   ]
  },
  {
   "title": "MySQL query cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/Qcache/" }
     ]
    }
   ]
  },
  {
   "title": "MySQL connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mysql",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "Connections" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "processes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "procs" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "WARNING",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procs",
     "select": [
      [
       { "params": [ "warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "procs" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "CRITICAL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procs",
     "select": [
      [
       { "params": [ "crit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "procs" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "DOWNTIME",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procs",
     "select": [
      [
       { "params": [ "downtime_depth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "procs" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Running processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "check_vmstat_procs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "running" }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "check_vmstat_procs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "blocked" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "load1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load1" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "load1-WARNING",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load1" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "load1-CRITICAL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "crit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load1" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "load5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load5" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "load5-WARNING",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load5" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "load5-CRITICAL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "crit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load5" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "load15",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load15" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "load15-WARNING",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load15" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "load15-CRITICAL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "crit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load15" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "DOWNTIME",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load",
     "select": [
      [
       { "params": [ "downtime_depth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "load1" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk $disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"max\") FROM \"disk\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "WARNING",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"warn\") FROM \"disk\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "CRITICAL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"crit\") FROM \"disk\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "crit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"value\") FROM \"disk\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "DOWNTIME",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"downtime_depth\")  * 100 FROM \"disk\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "downtime_depth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "swap" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "swap" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "WARNING",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "swap" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "CRITICAL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "crit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "swap" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "DOWNTIME",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "downtime_depth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "swap" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Page Swap in & out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "check_vmstat_paging",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pswpin" }
     ]
    },
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "check_vmstat_paging",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "pswpout" }
     ]
    }
   ]
  },
  {
   "title": "Users logged in",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "users",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "users",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "users" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "DOWNTIME",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "users",
     "select": [
      [
       { "params": [ "downtime_depth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "users" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "centreon_check_traffic",
     "query": "SELECT mean(\"value\")/mean(\"max\")*100 FROM \"centreon_check_traffic\" WHERE \"hostname\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($__interval), \"metric\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_traffic",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO - Readtime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_diskio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^readtime/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO - Writetime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_diskio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^writetime/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO - ReadIO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_diskio",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^readio/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO - WriteIO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_diskio",
     "query": "SELECT mean(\"value\") FROM \"centreon_check_diskio\" WHERE \"hostname\" =~ /^$hostname$/ AND \"metric\" =~ /^writeio/ AND $timeFilter GROUP BY time($__interval), \"metric\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^readio/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO - Utitlisation %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "centreon_check_diskio",
     "query": "SELECT mean(\"value\") FROM \"centreon_check_diskio\" WHERE \"hostname\" =~ /^$hostname$/ AND \"metric\" =~ /^writeio/ AND $timeFilter GROUP BY time($__interval), \"metric\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/^util/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read - IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "check_vmstat_diskio",
     "query": "SELECT mean(\"value\") FROM \"centreon_check_diskio\" WHERE \"hostname\" =~ /^$hostname$/ AND \"metric\" =~ /^writeio/ AND $timeFilter GROUP BY time($__interval), \"metric\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/read$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/da/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write - IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "metric" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "check_vmstat_diskio",
     "query": "SELECT mean(\"value\") FROM \"check_diskio\" WHERE \"hostname\" =~ /^$hostname$/ AND \"metric\" =~ /write$/ AND \"metric\" =~ /sda/ AND $timeFilter GROUP BY time($__interval), \"metric\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/write/" },
      { "condition": "AND", "key": "metric", "operator": "=~", "value": "/da/" }
     ]
    }
   ]
  }
 ]
}